package fmsteer

import (
	"crypto/rand"
	"encoding/hex"
	"flag"
	"fmt"
	"log"
	"strings"
	"time"
)

// Env names the crew can export once per session instead of repeating the
// same flags on every start/finish pair.
const (
	AgentIDEnv = "FIRSTMATE_AGENT_ID"
	ModelEnv   = "FIRSTMATE_MODEL"
	EffortEnv  = "FIRSTMATE_EFFORT"
)

// buildPath is the append-only build/deploy event ingest endpoint.
const buildPath = "/api/build-events"

// buildFlags are the fields shared by start and finish. Every field except
// the run id is optional on finish: the API carries a run's context forward
// from its previous event.
type buildFlags struct {
	runID     *string
	kind      *string
	target    *string
	agentID   *string
	model     *string
	effort    *string
	tokens    *int
	image     *string
	imageTag  *string
	cluster   *string
	namespace *string
	outcome   *string
	instance  *string
}

// cmdBuild dispatches `fm-steer build start|finish` and returns the process exit code.
func cmdBuild(args []string) int {
	if len(args) < 1 {
		return Usage()
	}
	switch args[0] {
	case "start":
		buildStart(args[1:])
	case "finish":
		buildFinish(args[1:])
	default:
		return Usage()
	}
	return 0
}

func buildStart(args []string) {
	fs := flag.NewFlagSet("build start", flag.ExitOnError)
	f := registerBuildFlags(fs)
	*f.agentID = Env(AgentIDEnv, "")
	*f.model = Env(ModelEnv, "")
	*f.effort = Env(EffortEnv, "")
	startedAt := fs.String("started-at", "", "RFC 3339 start time (default now)")
	_ = fs.Parse(args)

	if *f.kind == "" {
		log.Fatal("build start requires --kind (k8s, docker, bazel, ...)")
	}
	if *f.runID == "" {
		*f.runID = newRunID()
	}

	payload := buildPayload(f)
	payload["status"] = "started"
	payload["started_at"] = timestamp(*startedAt)
	postIngest(buildPath, *f.instance, payload)
}

func buildFinish(args []string) {
	fs := flag.NewFlagSet("build finish", flag.ExitOnError)
	f := registerBuildFlags(fs)
	status := fs.String("status", "success", "success|failure|cancelled")
	finishedAt := fs.String("finished-at", "", "RFC 3339 finish time (default now)")
	_ = fs.Parse(args)

	if *f.runID == "" {
		log.Fatal("build finish requires --run-id from the matching build start")
	}
	if !validFinishStatus(*status) {
		log.Fatalf("--status %q must be success, failure, or cancelled", *status)
	}

	payload := buildPayload(f)
	payload["status"] = *status
	payload["finished_at"] = timestamp(*finishedAt)
	postIngest(buildPath, *f.instance, payload)
}

func registerBuildFlags(fs *flag.FlagSet) buildFlags {
	return buildFlags{
		runID:     fs.String("run-id", "", "run id linking start to finish (generated by start when omitted)"),
		kind:      fs.String("kind", "", "build/deploy system: k8s, docker, bazel, ... (required on start)"),
		target:    fs.String("target", "", "what is built or deployed"),
		agentID:   fs.String("agent-id", "", "agent that performed the work"),
		model:     fs.String("model", "", "model that performed the work"),
		effort:    fs.String("effort", "", "reasoning effort the model ran at"),
		tokens:    fs.Int("tokens", 0, "cumulative tokens used by this run"),
		image:     fs.String("image", "", "image repository"),
		imageTag:  fs.String("image-tag", "", "image tag"),
		cluster:   fs.String("cluster", "", "cluster"),
		namespace: fs.String("namespace", "", "namespace"),
		outcome:   fs.String("outcome", "", "outcome notes"),
		instance:  fs.String("instance", Env("FIRSTMATE_INSTANCE", ""), "API base URL"),
	}
}

func buildPayload(f buildFlags) map[string]any {
	if *f.tokens < 0 {
		log.Fatalf("--tokens %d must not be negative", *f.tokens)
	}
	payload := map[string]any{"run_id": *f.runID}
	setIf(payload, "kind", *f.kind)
	setIf(payload, "target", *f.target)
	setIf(payload, "agent_id", *f.agentID)
	setIf(payload, "model", *f.model)
	setIf(payload, "effort", *f.effort)
	setIf(payload, "image", *f.image)
	setIf(payload, "image_tag", *f.imageTag)
	setIf(payload, "cluster", *f.cluster)
	setIf(payload, "namespace", *f.namespace)
	setIf(payload, "outcome", *f.outcome)
	if *f.tokens > 0 {
		payload["tokens"] = *f.tokens
	}
	return payload
}

// newRunID generates the correlation id a start event prints for the matching
// finish call.
func newRunID() string {
	raw := make([]byte, 8)
	if _, err := rand.Read(raw); err != nil {
		log.Fatal(err)
	}
	return "run-" + hex.EncodeToString(raw)
}

func validFinishStatus(status string) bool {
	switch status {
	case "success", "failure", "cancelled":
		return true
	default:
		return false
	}
}

// timestamp echoes an explicit RFC 3339 stamp and falls back to now, so a
// wrapper that already knows the real start time can report it.
func timestamp(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return time.Now().UTC().Format(time.RFC3339Nano)
	}
	if _, err := time.Parse(time.RFC3339, trimmed); err != nil {
		log.Fatal(fmt.Errorf("%q is not an RFC 3339 timestamp: %w", trimmed, err))
	}
	return trimmed
}
