defmodule FirstmatePortWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :firstmate_port

  # The session cookie is signed *and* encrypted, so its contents are opaque to
  # anyone without SECRET_KEY_BASE rather than merely tamper-evident. Both salts
  # are compile-time values because Plug.Session options are baked into the
  # endpoint module; `config/prod.exs` reads them from the environment at
  # release-build time so an operator can rotate them to invalidate every live
  # session. See `docs/security.md` — turning encryption on signs everyone out
  # once, at the deploy that introduces it.
  #
  # `Secure` follows `SESSION_COOKIE_SECURE` (true in prod builds) so the cookie
  # never travels over plain HTTP; dev and test keep it false so sign-in works
  # against `http://localhost`.
  #
  # `SameSite=Lax` rather than `Strict`: the OIDC provider bounces the browser
  # back to `/auth/oidc/callback` as a top-level cross-site GET, and `Strict`
  # would withhold the cookie on exactly that navigation. `Lax` still withholds
  # it from cross-site subresources and POSTs, and `protect_from_forgery` covers
  # state-changing requests.
  #
  # `max_age` matches the 12h Guardian token TTL, so the cookie cannot outlive
  # the credential inside it.
  @session_options [
    store: :cookie,
    key: "_firstmate_port_key",
    same_site: "Lax",
    http_only: true,
    max_age: 12 * 60 * 60,
    signing_salt: Application.compile_env!(:firstmate_port, [:session, :signing_salt]),
    encryption_salt: Application.compile_env!(:firstmate_port, [:session, :encryption_salt]),
    secure: Application.compile_env(:firstmate_port, [:session, :secure], false)
  ]

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  plug(:rewrite_proxy_scheme)

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :firstmate_port,
    gzip: not code_reloading?,
    only: FirstmatePortWeb.static_paths()
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug(AshAi.Mcp.Dev,
      # For many tools, you will need to set the `protocol_version_statement` to the older version.
      protocol_version_statement: "2024-11-05",
      otp_app: :firstmate_port,
      path: "/ash_ai/mcp"
    )

    socket("/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket)
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
    plug(AshPhoenix.Plug.CheckCodegenStatus)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :firstmate_port)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 8_000_000,
    body_reader: {FirstmatePortWeb.CacheBodyReader, :read_body, []}
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Plug.Session, @session_options)
  plug(FirstmatePortWeb.Router)

  defp rewrite_proxy_scheme(conn, _opts) do
    if Application.get_env(:firstmate_port, :trust_forwarded_proto, false) do
      Plug.RewriteOn.call(conn, Plug.RewriteOn.init([:x_forwarded_proto]))
    else
      conn
    end
  end
end
