defmodule FirstmatePort.Repo.Migrations.BuildEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:build_events, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :run_id, :text, null: false
      add :kind, :text, null: false
      add :target, :text, default: ""
      add :status, :text, null: false
      add :agent_id, :text, null: false
      add :model, :text, default: ""
      add :effort, :text, default: ""
      add :tokens, :bigint, default: 0
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :image, :text, default: ""
      add :image_tag, :text, default: ""
      add :cluster, :text, default: ""
      add :namespace, :text, default: ""
      add :outcome, :text, default: ""
      add :tenant_slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:build_events, [:tenant_slug, :run_id, :inserted_at])

    create table(:build_events_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :tenant_slug, :text, null: false

      add :version_source_id,
          references(:build_events,
            column: :id,
            name: "build_events_versions_version_source_id_fkey",
            type: :text,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:build_events_versions, "build_events_versions_version_source_id_fkey")

    drop table(:build_events_versions)

    drop_if_exists index(:build_events, [:tenant_slug, :run_id, :inserted_at])

    drop table(:build_events)
  end
end
