defmodule FirstmatePort.Repo.Migrations.AddFleetSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:fleet_documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_slug, :text, null: false
      add :source, :text, null: false
      add :source_id, :text, null: false
      add :title, :text, null: false
      add :url, :text, null: false, default: ""
      add :body, :text, null: false, default: ""
      add :document, :map, null: false, default: %{}
      add :search_text, :text, null: false, default: ""
      add :content_hash, :text, null: false, default: ""
      add :occurred_at, :utc_datetime_usec, null: false
      add :embedding, {:array, :float}
      add :embedding_model, :text, null: false, default: ""
      add :embedding_dimensions, :bigint, null: false, default: 0
      add :embedded_hash, :text, null: false, default: ""
      add :embedded_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:fleet_documents, [:tenant_slug, :source, :source_id],
             name: "fleet_documents_unique_source_index"
           )

    execute("""
    CREATE INDEX fleet_documents_search_gin
      ON fleet_documents
      USING GIN (to_tsvector('english', search_text))
    """)

    alter table(:tenants) do
      add :embedding_model, :text, null: false, default: ""
    end
  end

  def down do
    alter table(:tenants) do
      remove :embedding_model
    end

    execute("""
    DROP INDEX IF EXISTS fleet_documents_search_gin
    """)

    drop_if_exists unique_index(:fleet_documents, [:tenant_slug, :source, :source_id],
                     name: "fleet_documents_unique_source_index"
                   )

    drop table(:fleet_documents)
  end
end
