defmodule FirstmatePort.Repo.Migrations.AddProgressEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:progress_events, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :type, :text, null: false
      add :status, :text
      add :worker, :text, default: ""
      add :role, :text
      add :runtime, :text, default: ""
      add :model, :text, default: ""
      add :effort, :text, default: ""
      add :duration_ms, :bigint
      add :tokens, :bigint
      add :interrupted, :boolean
      add :detail, :text, default: ""
      add :occurred_at, :utc_datetime_usec, null: false
      add :tenant_slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:progress_items,
            column: :id,
            name: "progress_events_item_id_fkey",
            type: :text,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:progress_events, [:tenant_slug, :item_id])
  end

  def down do
    drop_if_exists index(:progress_events, [:tenant_slug, :item_id])

    drop constraint(:progress_events, "progress_events_item_id_fkey")

    drop table(:progress_events)
  end
end
