defmodule :"Elixir.FirstmatePort.Repo.Migrations.Usage-and-routing" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:usage_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :provider, :text, null: false
      add :label, :text, null: false
      add :unit, :text, null: false, default: "usd"
      add :allowance, :float
      add :used, :float, null: false, default: 0.0
      add :window, :text, null: false, default: "monthly"
      add :reset_at, :utc_datetime
      add :last_synced_at, :utc_datetime
      add :spend_priority, :bigint, null: false, default: 100
      add :source, :text, null: false, default: "manual"
      add :external_id, :text, default: ""
      add :notes, :text, default: ""
      add :tenant_slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:usage_accounts, [:tenant_slug, :provider, :label],
             name: "usage_accounts_unique_account_index"
           )

    create table(:usage_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :usage_account_id, :uuid, null: false
      add :used, :float, null: false
      add :source, :text, null: false, default: "manual"
      add :tenant_slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:usage_snapshots)

    drop_if_exists unique_index(:usage_accounts, [:tenant_slug, :provider, :label],
                     name: "usage_accounts_unique_account_index"
                   )

    drop table(:usage_accounts)
  end
end
