defmodule FirstmatePort.Repo.Migrations.AddTenantCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tenant_credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_slug, :text, null: false
      add :provider, :text, null: false
      add :key, :text, null: false
      add :description, :text, null: false, default: ""
      add :hint, :text, null: false, default: ""
      add :value_bytes, :bigint, null: false, default: 0
      add :rotated_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_value, :binary, null: false
    end

    create unique_index(:tenant_credentials, [:tenant_slug, :provider, :key],
             name: "tenant_credentials_unique_slot_index"
           )

    create table(:tenant_credentials_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :tenant_slug, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "tenant_credentials_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:tenant_credentials_versions, "tenant_credentials_versions_user_id_fkey")

    drop table(:tenant_credentials_versions)

    drop_if_exists unique_index(:tenant_credentials, [:tenant_slug, :provider, :key],
                     name: "tenant_credentials_unique_slot_index"
                   )

    drop table(:tenant_credentials)
  end
end
