defmodule FirstmatePort.Repo.Migrations.AddUsageSnapshotAccountIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:usage_snapshots, [:tenant_slug, :usage_account_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:usage_snapshots, [:tenant_slug, :usage_account_id, :inserted_at])
  end
end
