defmodule FirstmatePort.Repo.Migrations.DropUsageResetAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:usage_accounts) do
      remove :reset_at
    end
  end

  def down do
    alter table(:usage_accounts) do
      add :reset_at, :utc_datetime
    end
  end
end
