defmodule FirstmatePort.Repo.Migrations.DropUsageNotesAndSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:usage_accounts) do
      remove :source
      remove :notes
    end

    alter table(:usage_snapshots) do
      remove :source
    end
  end

  def down do
    alter table(:usage_snapshots) do
      add :source, :text, null: false, default: "manual"
    end

    alter table(:usage_accounts) do
      add :notes, :text, default: ""
      add :source, :text, null: false, default: "manual"
    end
  end
end
