defmodule FirstmatePort.Repo.Migrations.AddCliSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cli_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :jti, :text, null: false
      add :user_id, :uuid, null: false
      add :tenant_slug, :text, null: false
      add :instance, :text, null: false, default: ""
      add :user_agent, :text, null: false, default: ""
      add :expires_at, :utc_datetime_usec, null: false
      add :last_used_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:cli_sessions, [:jti], name: "cli_sessions_unique_jti_index")
  end

  def down do
    drop_if_exists unique_index(:cli_sessions, [:jti], name: "cli_sessions_unique_jti_index")

    drop table(:cli_sessions)
  end
end
