defmodule FirstmatePort.Repo.Migrations.ClaimDiscordApplication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenants) do
      add :discord_application_id, :text
    end

    create unique_index(:tenants, [:discord_application_id],
             name: "tenants_unique_discord_application_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:tenants, [:discord_application_id],
                     name: "tenants_unique_discord_application_id_index"
                   )

    alter table(:tenants) do
      remove :discord_application_id
    end
  end
end
