defmodule FirstmatePort.Repo.Migrations.AddInboxMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inbox_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :seq, :bigint, null: false
      add :task, :text, null: false
      add :body, :text, null: false
      add :delivery, :text, null: false, default: ""
      add :sender, :text, null: false, default: ""
      add :claimed_by, :text, null: false, default: ""
      add :status, :text, null: false, default: "pending"
      add :delivered_at, :utc_datetime_usec
      add :acked_at, :utc_datetime_usec
      add :tenant_slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:inbox_messages, [:tenant_slug, :seq],
             name: "inbox_messages_unique_seq_index"
           )

    create index(:inbox_messages, [:tenant_slug, :seq],
             name: "inbox_messages_pending_index",
             where: "status = 'pending'"
           )
  end

  def down do
    drop_if_exists index(:inbox_messages, [:tenant_slug, :seq],
                     name: "inbox_messages_pending_index"
                   )

    drop_if_exists unique_index(:inbox_messages, [:tenant_slug, :seq],
                     name: "inbox_messages_unique_seq_index"
                   )

    drop table(:inbox_messages)
  end
end
