defmodule FirstmatePort.Repo.Migrations.DropUnusedUsageAccountColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:usage_accounts) do
      remove :last_synced_at
      remove :external_id
    end
  end

  def down do
    alter table(:usage_accounts) do
      add :external_id, :text, default: ""
      add :last_synced_at, :utc_datetime
    end
  end
end
